# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- name: .Net Build
      #  uses: EasyDesk/action-dotnet-build@v1.0.0
      #  with:  
      #    #build-configuration: # optional, default is Release
      #    path: Telepathy.sln # optional, default is .
      - name: Build with dotnet
        run: dotnet build
              --configuration Release
      #- name: Test with dotnet
      #  run: dotnet test Telepathy.sln
      - name: Run a one-line script
        shell: cmd
        run: |
          cd LoadTest\bin\Release\net471
          LoadTest.exe timed 6565 60
          echo "Ended Load Test"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Telapathy # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: Telepathy\bin\Release\
          # The desired behavior if no files are found using the provided path.
      
      
